### ISSUE TITLE
Problems with site enable

### ISSUE THREAD

**Issue by webkernel** [small-tech/site.js#11]
Hi,

On my VPS I have a hugo site at ~/Sites/radiogeek.xyz/public. I log in to my server using a ssh connection and run site enable. When I type radiogeek.xyz the site is OK but on the next day I get 404 not found error.

What am I doing wrong?

Thanks.

**Comment by aral** [comment]
Hey @webkernel,

Sorry to hear you’re having issues. Can you tell me a few things to help me try and narrow it down:

- What version of Site.js are you running (run `site version` on the server)?

- What do you see when you type `site logs` on the server?

- What OS are you running on the server?

- Is the route you’re trying to hit a static page or is it in a .dynamic or .wildcard folder?

And could you possibly have run `site enable` on a different folder since then? Or sync to the server? If you’re getting a Site.js 404 error page, that means the Site.js daemon is running so I’m tying to understand what happened to the routes it had loaded.

**Comment by webkernel** [comment]
Hi Aral,

1) ct1ete@radiogeek:~$ site version

   🌱    Site.js

         Created September 1st, 2020 at 17:06:41

         Version 20200901170641-15.0.0-86cea75-linux/x64
         Node.js 12.16.2
         Hugo    0.64.1

         Base    https://sitejs.org/nexe/linux-x64-12.16.2
         Source  https://source.small-tech.org/site.js/app/-/tree/86cea75

2) ❨site.js❩ Tailing logs (press Ctrl+C to exit).

Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Sat 2020-07-04 13:57:33 UTC. --
Sep 02 00:41:52 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 00:59:34 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 01:17:05 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 01:18:59 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 01:31:32 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 02:40:23 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 02:40:23 radiogeek.xyz site[1007648]:    🤨    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain 95.179.152.131 (valid domain is radiogeek.xyz).
Sep 02 02:46:14 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 03:42:13 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 03:43:03 radiogeek.xyz site[1007648]:    🛰    ❨site.js❩ Running auto update check…
Sep 02 03:43:05 radiogeek.xyz site[1007648]:    🧙    ❨site.js❩ Root privileges required.
Sep 02 03:43:05 radiogeek.xyz site[1007648]:    ✨    ❨site.js❩ Starting privileged process…
Sep 02 03:43:05 radiogeek.xyz site[1007648]:    🧐    ❨site.js❩ Checking for release updates…
Sep 02 03:43:05 radiogeek.xyz site[1007648]:    👍    ❨site.js❩ You’re running the latest version of Site.js!
Sep 02 04:00:55 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 04:09:24 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 04:51:31 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 04:51:31 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          6.2 ms          0.6 kb          📄 /robots.txt
Sep 02 04:51:31 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 05:21:08 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 05:45:19 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 05:47:24 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 06:06:08 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 06:06:08 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 06:22:54 radiogeek.xyz site[1007648]:    🤨    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain 95.179.152.131 (valid domain is radiogeek.xyz).
Sep 02 07:23:26 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 07:29:40 radiogeek.xyz site[1007648]:    🤨    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain 95.179.152.131 (valid domain is radiogeek.xyz).
Sep 02 07:40:02 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          0.8 ms          0.6 kb          📄 /robots.txt
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          1.1 ms          0.6 kb          📄 /humans.txt
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          0.9 ms          0.6 kb          📄 /ads.txt
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 08:48:39 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          1.0 ms          0.6 kb          📄 /
Sep 02 08:50:03 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 09:22:58 radiogeek.xyz site[1007648]:    💞    HEAD          404          1.7 ms          0.6 kb          📄 /paulopinto
Sep 02 09:29:07 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 09:29:10 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          0.7 ms          0.6 kb          📄 /
Sep 02 09:29:14 radiogeek.xyz site[1007648]:    💞    ↓ GET          404          0.7 ms          0.6 kb          💠 /favicon.ico
Sep 02 09:31:51 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
Sep 02 09:31:52 radiogeek.xyz site[1007648]:    🤨    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain 95.179.152.131 (valid domain is radiogeek.xyz).
Sep 02 09:31:53 radiogeek.xyz site[1007648]:    👉    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.

3) Ubuntu 20.04.1 LTS

4) It is a static page

5) I always run site enable on my home directory

Thanks

**Comment by aral** [comment]
> 3. I always run site enable on my home directory

Hmm, that’s a lot of HTTP -> HTTPS redirections… but I think your real reason is this.

If your site is in `~/Sites/radiogeek.xyz/public`, do:

```
site enable ~/Sites/radiogeek.xyz/public
```

or 

```
cd ~/Sites/radiogeek.xyz/public
site enable 
```

Otherwise, what’s happening is you’re serving your home directory and the server can’t find an index.html in there.

Please do let me know if this fixes your issue.

(Also, I’m going to update the `status` command so that it shows you exactly which directory is being served. That should help debug issues like this.)

**Comment by webkernel** [comment]
Aral,

site enable ~/Sites/radiogeek.xyz/public WORKS!
I will come back if there's something worthing reporting.

Thanks.

**Comment by aral** [comment]
Very happy to hear it :)
