### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TeoDoe777** [small-tech/site.js#15]
After running your sitejs, my server under a gulp script writes an error in my browser - ERR_SSL_PROTOCOL_ERROR.

**Comment by aral** [comment]
Hi @TeoDoe777, I’m going to need more information in order to help you, I’m afraid :)

Is your project open source? Is there somewhere I can see your source code or can you please post more details on exactly what you’re doing so I can try to help? :)

**Comment by TeoDoe777** [comment]
how to remove your site.js completely ? with mac os \ it became unnecessary for me but because of it I constantly catch redirection to https.

**Comment by aral** [comment]
Please see https://github.com/small-tech/site.js/issues/3
