### ISSUE TITLE
`site help` shows banner’s lines displaced except the first one

### ISSUE THREAD

**Issue by alfonsomunozpomer** [small-tech/site.js#24]
I thought an image explains it better:
![image](https://user-images.githubusercontent.com/4425744/103217762-512b5c80-4911-11eb-89da-0319d5f5329a.png)

**Comment by aral** [comment]
Ah, that’s odd – which Terminal app is that in? Looks like the spacing is all off.

**Comment by alfonsomunozpomer** [comment]
I’m using [Tilix 1.9.1](https://gnunn1.github.io/tilix-web/) but I’m seeing the same behaviour with GNOME Terminal 3.38.0. It only happens with the `help` command. All others show the banner properly.

**Comment by aral** [comment]
My app, didn’t read it properly and see that it was the help screen that had the issue. Can reproduce.
