### ISSUE TITLE
Owncast's admin page URL says "Unauthorized"

### ISSUE THREAD

**Issue by wiwikuan** [small-tech/site.js#54]
The one-line Owncast deployment is awesome! I got my Owncast running just by:

`site enable --owncast`

I can get to the home page of Owncast, the SSL is working good. But I can't go to Owncast's admin page by go to https://example.com/admin, it just says "Unauthorized".

Am I missing something, am I suppose to go to the Owncast admin page via some other URLs? I googled about this problem but can't find anything related to this.

Thanks for the help!

**Comment by aral** [comment]
Hey there, thanks for the report. Does this happen when you hit the page or when you enter the default authentication details?

https://owncast.online/docs/configuration/

**Comment by wiwikuan** [comment]
When I hit the URL it gives me a white blank page with one line of text saying "Unauthorized".

I'll leave the site live, you can take a look if you want to:
https://two.wiwi.video/admin/

Thanks!

**Comment by wiwikuan** [comment]
Later I found out that the problem is the Brave Browser, if I disable the built-in tracker/ad blocker, the admin page loads fine.
