### ISSUE TITLE
[documentation] a brief explanation of what's this

### ISSUE THREAD

**Issue by pedro-nonfree** [small-tech/site.js#7]
I arrived here from one video you posted and some friend recommend [1]. Congratulations explaining so well the problem. We differ in the way we see the solution.

At the end you presented this software project. Can you please explain what is doing? I can get an idea, but I think it would be nice to find this more immediately. Because I would like to not trust you, but trust myself and my technical background to understand how good is your solution and if I then would test it or recommend to others.

Thanks

[1] https://vimeo.com/443408666

**Comment by aral** [comment]
Hi @pedro-nonfree, thank you for your feedback.

Have you seen the web site for the project: https://sitejs.org

Does that answer your question? If not, what exactly would you like to see to give you a better idea of what this project does?

**Comment by aral** [comment]
Thanks for the update @pedro-nonfree, I understand what you mean. Site.js will be used for [2] but, at the moment, my goal is to ensure that it fulfills [1] first. (We are slowly building up to it, ensuring that it covers the use cases we have currently so we can run everything we are currently running on it and to add the aspects of [2] progressively on top of that.) Going to close this but appreciate the feedback. We’re going to get there eventually ;)
